### PR TITLE
feat(ui): extend agent-avatar tooltip to 10 chars

### PR DESCRIPTION
**Pull request by mattyg**

### CODE REVIEW

**Comment by mattyg** [comment]
any thoughts @guillemcordoba Or maybe instead I could specify the substring length via a property?

**Comment by guillemcordoba** [comment]
Hum honestly I think that that tooltip should display the nickname of the agent, not really their pubkey... What do you think about that? It's obviously not on you to change that BTW.

**Comment by mattyg** [comment]
> Hum honestly I think that that tooltip should display the nickname of the agent, not really their pubkey... What do you think about that? It's obviously not on you to change that BTW.

Idk I know we're trying not to show hashes anywhere for good UX. I'd love to have visual hashes that completely cover the hash space with 0 collisions. But without that I think we should provide some way for users to double check the hash themselves for cases where a malicious agent is intentionally trying to impersonate another.

**Comment by guillemcordoba** [comment]
Yeah okey that makes sense, then the solution I'd give is when you hover on an agent's avatar, it shows a tooltip that contains the identicon, the pubkey, a way to copy the pubkey, the nickname... Kind of like when you click on an agent's avatar in discord. Would that solve it?

**Comment by mattyg** [comment]
> Yeah okey that makes sense, then the solution I'd give is when you hover on an agent's avatar, it shows a tooltip that contains the identicon, the pubkey, a way to copy the pubkey, the nickname... Kind of like when you click on an agent's avatar in discord. Would that solve it?

Yeah that sounds great.

Though for my app I have that same UX implemented manually with app-specific styling.  So for me right now it makes more sense to just implement the agent pub key tooltip in app rather than expecting it to be part of the profiles components.

I'm gonna close this PR.

**Pull request closed without merging**
